/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/airports': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Autocompletado de aeropuertos
     * @description Devuelve aeropuertos cuyo código IATA, ciudad o nombre empiezan por (o
     *     contienen) el texto indicado. Pensado para un campo de autocompletado:
     *     es barato, sin efectos secundarios y cacheable.
     */
    get: operations['searchAirports'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/offers/search': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Buscar ofertas de vuelo
     * @description Consulta al proveedor de vuelos configurado (estilo Amadeus) y devuelve
     *     ofertas normalizadas. Cada oferta indica si puede emitirse en **un
     *     solo ticket**: es decir, si la aerolínea validadora tiene acuerdo
     *     interline con todas las aerolíneas operadoras.
     *
     *     La oferta queda disponible para reservar mediante `offerId` hasta
     *     `expiresAt`. Esta operación no modifica estado (POST por el tamaño y
     *     la estructura de los criterios).
     */
    post: operations['searchOffers'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/bookings': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Listar reservas (paginado)
     * @description Lista reservas ordenadas de la más reciente a la más antigua. Si se
     *     envía `X-Tenant`, solo se devuelven las reservas cuya aerolínea
     *     validadora es ese tenant.
     */
    get: operations['listBookings'];
    put?: never;
    /**
     * Crear una reserva a partir de una oferta
     * @description Crea la reserva, la tarifica contra la oferta y solicita los segmentos a
     *     las aerolíneas operadoras. Si todo va bien la reserva queda en `HELD`
     *     (algunos segmentos pueden seguir en `UC`, pendientes de confirmación).
     *
     *     **Idempotencia** (según draft-ietf-httpapi-idempotency-key-header):
     *     - El header `Idempotency-Key` es obligatorio (`400` si falta).
     *     - Repetir la misma clave con el mismo cuerpo devuelve la respuesta
     *       original (mismo `201` y mismo localizador) con
     *       `Idempotency-Replayed: true`, sin crear otra reserva.
     *     - Repetir la clave con un cuerpo distinto devuelve `422`.
     *     - Si la petición original aún se está procesando devuelve `409`.
     */
    post: operations['createBooking'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/bookings/{locator}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Consultar una reserva por localizador
     * @description Devuelve la reserva completa: pasajeros, segmentos con su estado,
     *     pagos, tickets, la línea de tiempo de estados (`statusHistory`) y las
     *     acciones disponibles en el estado actual (`availableActions`).
     */
    get: operations['getBooking'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/bookings/{locator}/payments': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Autorizar el pago de una reserva
     * @description Autoriza (sin capturar) el pago de una reserva en `HELD`: efectivo,
     *     millas o mixto. Las millas se bloquean (hold) en el programa de
     *     lealtad. La reserva pasa a `PAYMENT_AUTHORIZED`. La captura ocurre al
     *     emitir el ticket.
     *
     *     Reglas:
     *     - `CASH`: solo `cash`, debe cubrir el total de la tarifa.
     *     - `MILES`: solo `miles`, debe cubrir `milesEquivalent`.
     *     - `MIXED`: `cash` y `miles` > 0; juntos deben cubrir la tarifa de forma
     *       proporcional (`cash/total + miles/milesEquivalent ≥ 1`).
     *
     *     Si la forma del cuerpo no corresponde al método (p. ej. `CASH` sin
     *     `cash`) se responde `400`; si los importes no cubren la tarifa, `422`.
     *     Exige `Idempotency-Key` con la misma semántica que la creación.
     */
    post: operations['authorizePayment'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/bookings/{locator}/ticket': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Emitir el ticket único de la reserva
     * @description Ejecuta la saga de emisión:
     *     1. Verifica el acuerdo interline de la validadora con todas las
     *        operadoras (`422` si falta alguno; la reserva no cambia).
     *     2. Confirma los segmentos `UC` con reintentos.
     *     3. Captura el pago y emite un ticket por pasajero → `TICKETED`.
     *
     *     Si algún segmento sigue en `UC` tras los reintentos se compensa:
     *     se cancelan los segmentos confirmados, se libera la autorización de
     *     pago / hold de millas, la reserva pasa a `FAILED` y se responde `422`
     *     con `bookingStatus: FAILED`.
     *
     *     Es idempotente por estado: sobre una reserva ya `TICKETED` devuelve
     *     `200` con los mismos tickets.
     */
    post: operations['issueTicket'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/bookings/{locator}/cancel': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Cancelar una reserva
     * @description Cancela los segmentos activos, libera pagos autorizados / holds de
     *     millas y pasa la reserva a `CANCELLED`. Una reserva `TICKETED` no se
     *     puede cancelar por esta vía (requiere anulación/reembolso, fuera de
     *     alcance) → `409`. Es idempotente: cancelar una reserva ya cancelada
     *     devuelve `200`.
     */
    post: operations['cancelBooking'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * @description Código IATA de aerolínea (2 caracteres alfanuméricos, no ambos dígitos).
     * @example AV
     */
    AirlineCode: string;
    /**
     * @description Código IATA de aeropuerto (3 letras).
     * @example BOG
     */
    AirportCode: string;
    /**
     * @description Localizador tipo PNR de 6 caracteres. Se excluyen 0, 1, I y O para
     *     evitar confusiones al dictarlo.
     * @example K7Q2MX
     */
    BookingLocator: string;
    /**
     * @description Fecha y hora LOCAL del aeropuerto, sin offset (ISO-8601).
     * @example 2026-11-20T19:05:00
     */
    LocalDateTime: string;
    Money: {
      /**
       * @description Importe decimal (se mapea a BigDecimal).
       * @example 1849.6
       */
      amount: number;
      /**
       * @description Código de moneda ISO 4217.
       * @example USD
       */
      currency: string;
    };
    Airport: {
      code: components['schemas']['AirportCode'];
      /** @example El Dorado International */
      name: string;
      /** @example Bogotá */
      city: string;
      /**
       * @description Código de país ISO 3166-1 alfa-2.
       * @example CO
       */
      countryCode: string;
    };
    /**
     * @description Composición del grupo. Mínimo 1 adulto, máximo 9 asientos
     *     (adultos + niños) y nunca más infantes que adultos.
     */
    PassengerCounts: {
      /**
       * Format: int32
       * @example 2
       */
      adults: number;
      /**
       * Format: int32
       * @default 0
       * @example 0
       */
      children: number;
      /**
       * Format: int32
       * @default 0
       * @example 1
       */
      infants: number;
    };
    OfferSearchRequest: {
      origin: components['schemas']['AirportCode'];
      destination: components['schemas']['AirportCode'];
      /**
       * Format: date
       * @description Fecha de salida (no puede ser pasada).
       * @example 2026-11-20
       */
      departureDate: string;
      /**
       * Format: date
       * @description Fecha de regreso; si se omite, la búsqueda es solo ida.
       * @example 2026-11-27
       */
      returnDate?: string;
      passengers: components['schemas']['PassengerCounts'];
      validatingAirline?: components['schemas']['AirlineCode'];
    };
    OfferSearchResponse: {
      /**
       * Format: int32
       * @example 1
       */
      count: number;
      offers: components['schemas']['FlightOffer'][];
    };
    FlightOffer: {
      /**
       * @description Identificador opaco de la oferta, válido hasta `expiresAt`.
       * @example OF-7f3c9a1e
       */
      offerId: string;
      validatingAirline: components['schemas']['AirlineCode'];
      interline: components['schemas']['InterlineEligibility'];
      itineraries: components['schemas']['Itinerary'][];
      price: components['schemas']['Fare'];
      /**
       * Format: date-time
       * @example 2026-11-01T15:30:00Z
       */
      expiresAt: string;
    };
    InterlineEligibility: {
      /** @description true si la validadora tiene acuerdo interline con todas las operadoras. */
      singleTicketEligible: boolean;
      operatingAirlines: components['schemas']['AirlineCode'][];
      /** @description Operadoras con las que la validadora NO tiene acuerdo. */
      missingAgreements: components['schemas']['AirlineCode'][];
    };
    Itinerary: {
      /** @enum {string} */
      direction: 'OUTBOUND' | 'INBOUND';
      /**
       * @description Duración total ISO-8601 (incluye conexiones).
       * @example PT14H10M
       */
      duration: string;
      segments: components['schemas']['FlightSegment'][];
    };
    FlightSegment: {
      operatingAirline: components['schemas']['AirlineCode'];
      /**
       * @description Número de vuelo sin el código de aerolínea (1–4 dígitos y sufijo opcional).
       * @example 26
       */
      flightNumber: string;
      origin: components['schemas']['AirportCode'];
      destination: components['schemas']['AirportCode'];
      departureAt: components['schemas']['LocalDateTime'];
      arrivalAt: components['schemas']['LocalDateTime'];
    };
    Fare: {
      total: components['schemas']['Money'];
      /**
       * Format: int64
       * @description Precio total expresado en millas del programa de la validadora.
       * @example 184960
       */
      milesEquivalent: number;
    };
    /**
     * @description `ADT` adulto (≥ 12 años), `CHD` niño (2–11), `INF` infante (< 2, viaja
     *     en brazos de un adulto). La edad se calcula a la fecha del primer vuelo.
     * @enum {string}
     */
    PassengerType: 'ADT' | 'CHD' | 'INF';
    PassengerInput: {
      /**
       * @description Referencia local del cliente para enlazar infantes con su adulto.
       * @example P1
       */
      ref: string;
      type: components['schemas']['PassengerType'];
      /** @example Ana */
      firstName: string;
      /** @example Pérez */
      lastName: string;
      /**
       * Format: date
       * @example 1990-04-12
       */
      dateOfBirth: string;
      /**
       * @description Obligatorio solo para `INF`; `ref` del adulto que lo lleva.
       * @example P1
       */
      associatedAdultRef?: string;
    };
    Contact: {
      /**
       * Format: email
       * @example ana.perez@example.com
       */
      email: string;
      /**
       * @description Teléfono en formato E.164.
       * @example +573001234567
       */
      phone?: string;
    };
    CreateBookingRequest: {
      /** @example OF-7f3c9a1e */
      offerId: string;
      passengers: components['schemas']['PassengerInput'][];
      contact: components['schemas']['Contact'];
    };
    /** @enum {string} */
    PaymentMethod: 'CASH' | 'MILES' | 'MIXED';
    MilesRedemption: {
      /**
       * Format: int64
       * @example 184960
       */
      amount: number;
      /**
       * @description Número de socio del programa de lealtad de la validadora.
       * @example 12345678901
       */
      memberNumber: string;
    };
    /** @description Según `method` se exige `cash`, `miles` o ambos (ver la operación). */
    PaymentRequest: {
      method: components['schemas']['PaymentMethod'];
      cash?: components['schemas']['Money'];
      miles?: components['schemas']['MilesRedemption'];
    };
    CancelBookingRequest: {
      /** @example El cliente cambió sus planes */
      reason?: string;
    };
    /**
     * @description Máquina de estados: `DRAFT → PRICED → HELD → PAYMENT_AUTHORIZED →
     *     TICKETED`. Desde cualquier estado no terminal se puede salir a
     *     `FAILED` o `CANCELLED`. `TICKETED`, `FAILED` y `CANCELLED` son
     *     terminales.
     * @enum {string}
     */
    BookingStatus:
      'DRAFT' | 'PRICED' | 'HELD' | 'PAYMENT_AUTHORIZED' | 'TICKETED' | 'FAILED' | 'CANCELLED';
    /**
     * @description `HK` confirmado, `UC` no confirmado, `XX` cancelado.
     * @enum {string}
     */
    SegmentStatus: 'HK' | 'UC' | 'XX';
    /**
     * @description `AUTHORIZED` autorizado/bloqueado, `CAPTURED` cobrado, `RELEASED` liberado.
     * @enum {string}
     */
    PaymentStatus: 'AUTHORIZED' | 'CAPTURED' | 'RELEASED';
    /**
     * @description Acción que el cliente puede ejecutar en el estado actual.
     * @enum {string}
     */
    BookingAction: 'PAY' | 'TICKET' | 'CANCEL';
    Passenger: {
      /** Format: uuid */
      id: string;
      type: components['schemas']['PassengerType'];
      firstName: string;
      lastName: string;
      /** Format: date */
      dateOfBirth: string;
      /**
       * Format: uuid
       * @description Solo para `INF`.
       */
      associatedAdultId?: string;
    };
    Segment: components['schemas']['FlightSegment'] & {
      /** Format: uuid */
      id: string;
      status: components['schemas']['SegmentStatus'];
    };
    MilesAmount: {
      /**
       * Format: int64
       * @example 184960
       */
      amount: number;
      /**
       * @description Número de socio enmascarado.
       * @example *******8901
       */
      memberNumber: string;
    };
    Payment: {
      /** Format: uuid */
      id: string;
      method: components['schemas']['PaymentMethod'];
      cash?: components['schemas']['Money'];
      miles?: components['schemas']['MilesAmount'];
      status: components['schemas']['PaymentStatus'];
      /** Format: date-time */
      createdAt: string;
    };
    Ticket: {
      /**
       * @description Número de ticket de 13 dígitos (prefijo contable de 3 dígitos de la validadora + 10 dígitos).
       * @example 1342412345678
       */
      number: string;
      /** Format: uuid */
      passengerId: string;
      /** Format: date-time */
      issuedAt: string;
    };
    StatusChange: {
      from?: components['schemas']['BookingStatus'];
      to: components['schemas']['BookingStatus'];
      /** Format: date-time */
      at: string;
      reason?: string;
    };
    Booking: {
      locator: components['schemas']['BookingLocator'];
      status: components['schemas']['BookingStatus'];
      validatingAirline: components['schemas']['AirlineCode'];
      fare?: components['schemas']['Fare'];
      contact?: components['schemas']['Contact'];
      passengers: components['schemas']['Passenger'][];
      segments: components['schemas']['Segment'][];
      payments: components['schemas']['Payment'][];
      tickets: components['schemas']['Ticket'][];
      /** @description Línea de tiempo de estados, del más antiguo al más reciente. */
      statusHistory: components['schemas']['StatusChange'][];
      availableActions: components['schemas']['BookingAction'][];
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    BookingSummary: {
      locator: components['schemas']['BookingLocator'];
      status: components['schemas']['BookingStatus'];
      validatingAirline: components['schemas']['AirlineCode'];
      origin: components['schemas']['AirportCode'];
      destination: components['schemas']['AirportCode'];
      firstDepartureAt: components['schemas']['LocalDateTime'];
      /** Format: int32 */
      passengerCount: number;
      /** Format: date-time */
      createdAt: string;
    };
    BookingPage: {
      items: components['schemas']['BookingSummary'][];
      /** Format: int32 */
      page: number;
      /** Format: int32 */
      size: number;
      /** Format: int64 */
      totalElements: number;
      /** Format: int32 */
      totalPages: number;
    };
    FieldError: {
      /** @example passengers[0].dateOfBirth */
      field: string;
      /** @example es obligatorio */
      message: string;
    };
    /** @description Problem Details (RFC 7807) con extensiones propias. */
    Problem: {
      /**
       * Format: uri
       * @description URI que identifica el tipo de problema.
       */
      type: string;
      title: string;
      /** Format: int32 */
      status: number;
      detail?: string;
      /**
       * @description Ruta de la petición que originó el problema.
       * @example /api/v1/bookings/K7Q2MX/ticket
       */
      instance?: string;
      /**
       * @description Código estable legible por máquina (extensión).
       * @example INFANT_RULE_VIOLATION
       */
      code?: string;
      /** @description Identificador de correlación de la petición (extensión). */
      correlationId?: string;
      bookingStatus?: components['schemas']['BookingStatus'];
      locator?: components['schemas']['BookingLocator'];
      /** @description Errores por campo (solo en 400 de validación). */
      errors?: components['schemas']['FieldError'][];
    };
  };
  responses: {
    /** @description Petición mal formada o con datos que no cumplen el formato. */
    BadRequest: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        /**
         * @example {
         *       "type": "https://interline.example.com/problems/validation-error",
         *       "title": "Petición inválida",
         *       "status": 400,
         *       "detail": "La petición contiene 2 errores de validación.",
         *       "code": "VALIDATION_ERROR",
         *       "correlationId": "8d0c2f0e-5b1a-4f7e-9a51-2c1f0f6a9b11",
         *       "errors": [
         *         {
         *           "field": "passengers[0].dateOfBirth",
         *           "message": "es obligatorio"
         *         },
         *         {
         *           "field": "origin",
         *           "message": "debe ser un código IATA de 3 letras"
         *         }
         *       ]
         *     }
         */
        'application/problem+json': components['schemas']['Problem'];
      };
    };
    /** @description El recurso no existe. */
    NotFound: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        /**
         * @example {
         *       "type": "https://interline.example.com/problems/booking-not-found",
         *       "title": "Reserva no encontrada",
         *       "status": 404,
         *       "detail": "No existe una reserva con localizador K7Q2MX.",
         *       "code": "BOOKING_NOT_FOUND",
         *       "correlationId": "8d0c2f0e-5b1a-4f7e-9a51-2c1f0f6a9b11"
         *     }
         */
        'application/problem+json': components['schemas']['Problem'];
      };
    };
    /** @description Conflicto con el estado actual del recurso. */
    Conflict: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/problem+json': components['schemas']['Problem'];
      };
    };
    /** @description La petición es válida pero viola una regla de negocio. */
    UnprocessableEntity: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/problem+json': components['schemas']['Problem'];
      };
    };
    /** @description El proveedor de vuelos no está disponible (timeout o circuit breaker abierto). */
    ServiceUnavailable: {
      headers: {
        /** @description Segundos recomendados antes de reintentar. */
        'Retry-After'?: number;
        [name: string]: unknown;
      };
      content: {
        /**
         * @example {
         *       "type": "https://interline.example.com/problems/provider-unavailable",
         *       "title": "Proveedor no disponible",
         *       "status": 503,
         *       "detail": "El proveedor de vuelos no respondió a tiempo.",
         *       "code": "PROVIDER_UNAVAILABLE",
         *       "correlationId": "8d0c2f0e-5b1a-4f7e-9a51-2c1f0f6a9b11"
         *     }
         */
        'application/problem+json': components['schemas']['Problem'];
      };
    };
  };
  parameters: {
    /**
     * @description Identificador de correlación; se propaga a logs, trazas y proveedores externos.
     * @example 8d0c2f0e-5b1a-4f7e-9a51-2c1f0f6a9b11
     */
    CorrelationId: string;
    /** @description Código IATA de la aerolínea white-label que usa el cliente. */
    Tenant: components['schemas']['AirlineCode'];
    /**
     * @description Clave única por intento lógico de operación (se recomienda un UUID v4).
     * @example 3f1b8c52-6a0e-4d1f-9a47-0c2d5e8b7a19
     */
    IdempotencyKey: string;
    /** @description Localizador de la reserva (PNR). */
    Locator: components['schemas']['BookingLocator'];
  };
  requestBodies: never;
  headers: {
    /** @description Identificador de correlación de la petición (recibido o generado). */
    CorrelationId: string;
    /** @description `true` si la respuesta es la repetición de una petición idempotente anterior. */
    IdempotencyReplayed: boolean;
  };
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  searchAirports: {
    parameters: {
      query: {
        /**
         * @description Texto a buscar (mínimo 2 caracteres). No distingue mayúsculas ni tildes.
         * @example mad
         */
        query: string;
        /** @description Número máximo de resultados. */
        limit?: number;
      };
      header?: {
        /**
         * @description Identificador de correlación; se propaga a logs, trazas y proveedores externos.
         * @example 8d0c2f0e-5b1a-4f7e-9a51-2c1f0f6a9b11
         */
        'X-Correlation-ID'?: components['parameters']['CorrelationId'];
        /** @description Código IATA de la aerolínea white-label que usa el cliente. */
        'X-Tenant'?: components['parameters']['Tenant'];
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Aeropuertos que coinciden (puede ser una lista vacía). */
      200: {
        headers: {
          'X-Correlation-ID': components['headers']['CorrelationId'];
          [name: string]: unknown;
        };
        content: {
          /**
           * @example [
           *       {
           *         "code": "MAD",
           *         "name": "Adolfo Suárez Madrid-Barajas",
           *         "city": "Madrid",
           *         "countryCode": "ES"
           *       }
           *     ]
           */
          'application/json': components['schemas']['Airport'][];
        };
      };
      400: components['responses']['BadRequest'];
    };
  };
  searchOffers: {
    parameters: {
      query?: never;
      header?: {
        /**
         * @description Identificador de correlación; se propaga a logs, trazas y proveedores externos.
         * @example 8d0c2f0e-5b1a-4f7e-9a51-2c1f0f6a9b11
         */
        'X-Correlation-ID'?: components['parameters']['CorrelationId'];
        /** @description Código IATA de la aerolínea white-label que usa el cliente. */
        'X-Tenant'?: components['parameters']['Tenant'];
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['OfferSearchRequest'];
      };
    };
    responses: {
      /** @description Ofertas encontradas (puede ser una lista vacía). */
      200: {
        headers: {
          'X-Correlation-ID': components['headers']['CorrelationId'];
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "count": 1,
           *       "offers": [
           *         {
           *           "offerId": "OF-7f3c9a1e",
           *           "validatingAirline": "AV",
           *           "interline": {
           *             "singleTicketEligible": true,
           *             "operatingAirlines": [
           *               "AV",
           *               "IB"
           *             ],
           *             "missingAgreements": []
           *           },
           *           "itineraries": [
           *             {
           *               "direction": "OUTBOUND",
           *               "duration": "PT14H10M",
           *               "segments": [
           *                 {
           *                   "operatingAirline": "AV",
           *                   "flightNumber": "26",
           *                   "origin": "BOG",
           *                   "destination": "MAD",
           *                   "departureAt": "2026-11-20T19:05:00",
           *                   "arrivalAt": "2026-11-21T11:40:00"
           *                 },
           *                 {
           *                   "operatingAirline": "IB",
           *                   "flightNumber": "3234",
           *                   "origin": "MAD",
           *                   "destination": "FCO",
           *                   "departureAt": "2026-11-21T13:15:00",
           *                   "arrivalAt": "2026-11-21T15:45:00"
           *                 }
           *               ]
           *             }
           *           ],
           *           "price": {
           *             "total": {
           *               "amount": 1849.6,
           *               "currency": "USD"
           *             },
           *             "milesEquivalent": 184960
           *           },
           *           "expiresAt": "2026-11-01T15:30:00Z"
           *         }
           *       ]
           *     }
           */
          'application/json': components['schemas']['OfferSearchResponse'];
        };
      };
      400: components['responses']['BadRequest'];
      422: components['responses']['UnprocessableEntity'];
      503: components['responses']['ServiceUnavailable'];
    };
  };
  listBookings: {
    parameters: {
      query?: {
        /** @description Filtra por uno o varios estados (`?status=HELD&status=TICKETED`). */
        status?: components['schemas']['BookingStatus'][];
        /** @description Número de página, empezando en 0. */
        page?: number;
        /** @description Tamaño de página. */
        size?: number;
      };
      header?: {
        /**
         * @description Identificador de correlación; se propaga a logs, trazas y proveedores externos.
         * @example 8d0c2f0e-5b1a-4f7e-9a51-2c1f0f6a9b11
         */
        'X-Correlation-ID'?: components['parameters']['CorrelationId'];
        /** @description Código IATA de la aerolínea white-label que usa el cliente. */
        'X-Tenant'?: components['parameters']['Tenant'];
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Página de reservas. */
      200: {
        headers: {
          'X-Correlation-ID': components['headers']['CorrelationId'];
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "page": 0,
           *       "size": 20,
           *       "totalElements": 1,
           *       "totalPages": 1,
           *       "items": [
           *         {
           *           "locator": "K7Q2MX",
           *           "status": "HELD",
           *           "validatingAirline": "AV",
           *           "origin": "BOG",
           *           "destination": "FCO",
           *           "firstDepartureAt": "2026-11-20T19:05:00",
           *           "passengerCount": 3,
           *           "createdAt": "2026-11-01T15:12:03Z"
           *         }
           *       ]
           *     }
           */
          'application/json': components['schemas']['BookingPage'];
        };
      };
      400: components['responses']['BadRequest'];
    };
  };
  createBooking: {
    parameters: {
      query?: never;
      header: {
        /**
         * @description Identificador de correlación; se propaga a logs, trazas y proveedores externos.
         * @example 8d0c2f0e-5b1a-4f7e-9a51-2c1f0f6a9b11
         */
        'X-Correlation-ID'?: components['parameters']['CorrelationId'];
        /** @description Código IATA de la aerolínea white-label que usa el cliente. */
        'X-Tenant'?: components['parameters']['Tenant'];
        /**
         * @description Clave única por intento lógico de operación (se recomienda un UUID v4).
         * @example 3f1b8c52-6a0e-4d1f-9a47-0c2d5e8b7a19
         */
        'Idempotency-Key': components['parameters']['IdempotencyKey'];
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        /**
         * @example {
         *       "offerId": "OF-7f3c9a1e",
         *       "contact": {
         *         "email": "ana.perez@example.com",
         *         "phone": "+573001234567"
         *       },
         *       "passengers": [
         *         {
         *           "ref": "P1",
         *           "type": "ADT",
         *           "firstName": "Ana",
         *           "lastName": "Pérez",
         *           "dateOfBirth": "1990-04-12"
         *         },
         *         {
         *           "ref": "P2",
         *           "type": "ADT",
         *           "firstName": "Luis",
         *           "lastName": "Gómez",
         *           "dateOfBirth": "1988-09-30"
         *         },
         *         {
         *           "ref": "P3",
         *           "type": "INF",
         *           "firstName": "Sofía",
         *           "lastName": "Gómez",
         *           "dateOfBirth": "2026-01-15",
         *           "associatedAdultRef": "P2"
         *         }
         *       ]
         *     }
         */
        'application/json': components['schemas']['CreateBookingRequest'];
      };
    };
    responses: {
      /** @description Reserva creada (o respuesta original repetida por idempotencia). */
      201: {
        headers: {
          /**
           * @description URL de la reserva creada.
           * @example /api/v1/bookings/K7Q2MX
           */
          Location?: string;
          'Idempotency-Replayed': components['headers']['IdempotencyReplayed'];
          'X-Correlation-ID': components['headers']['CorrelationId'];
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Booking'];
        };
      };
      400: components['responses']['BadRequest'];
      /** @description La oferta no existe o ya no está disponible. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "type": "https://interline.example.com/problems/offer-not-found",
           *       "title": "Oferta no encontrada",
           *       "status": 404,
           *       "detail": "La oferta OF-7f3c9a1e no existe.",
           *       "code": "OFFER_NOT_FOUND",
           *       "correlationId": "8d0c2f0e-5b1a-4f7e-9a51-2c1f0f6a9b11"
           *     }
           */
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      409: components['responses']['Conflict'];
      /**
       * @description Regla de negocio incumplida. Si la reserva llegó a crearse y se
       *     compensó (una operadora rechazó un segmento), el problema incluye
       *     `locator` y `bookingStatus: FAILED`.
       */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
    };
  };
  getBooking: {
    parameters: {
      query?: never;
      header?: {
        /**
         * @description Identificador de correlación; se propaga a logs, trazas y proveedores externos.
         * @example 8d0c2f0e-5b1a-4f7e-9a51-2c1f0f6a9b11
         */
        'X-Correlation-ID'?: components['parameters']['CorrelationId'];
        /** @description Código IATA de la aerolínea white-label que usa el cliente. */
        'X-Tenant'?: components['parameters']['Tenant'];
      };
      path: {
        /** @description Localizador de la reserva (PNR). */
        locator: components['parameters']['Locator'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Reserva encontrada, con su línea de tiempo de estados. */
      200: {
        headers: {
          'X-Correlation-ID': components['headers']['CorrelationId'];
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Booking'];
        };
      };
      400: components['responses']['BadRequest'];
      404: components['responses']['NotFound'];
    };
  };
  authorizePayment: {
    parameters: {
      query?: never;
      header: {
        /**
         * @description Identificador de correlación; se propaga a logs, trazas y proveedores externos.
         * @example 8d0c2f0e-5b1a-4f7e-9a51-2c1f0f6a9b11
         */
        'X-Correlation-ID'?: components['parameters']['CorrelationId'];
        /** @description Código IATA de la aerolínea white-label que usa el cliente. */
        'X-Tenant'?: components['parameters']['Tenant'];
        /**
         * @description Clave única por intento lógico de operación (se recomienda un UUID v4).
         * @example 3f1b8c52-6a0e-4d1f-9a47-0c2d5e8b7a19
         */
        'Idempotency-Key': components['parameters']['IdempotencyKey'];
      };
      path: {
        /** @description Localizador de la reserva (PNR). */
        locator: components['parameters']['Locator'];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['PaymentRequest'];
      };
    };
    responses: {
      /** @description Pago autorizado; devuelve la reserva actualizada. */
      201: {
        headers: {
          /**
           * @description URL de la reserva.
           * @example /api/v1/bookings/K7Q2MX
           */
          Location?: string;
          'Idempotency-Replayed': components['headers']['IdempotencyReplayed'];
          'X-Correlation-ID': components['headers']['CorrelationId'];
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Booking'];
        };
      };
      400: components['responses']['BadRequest'];
      404: components['responses']['NotFound'];
      409: components['responses']['Conflict'];
      422: components['responses']['UnprocessableEntity'];
    };
  };
  issueTicket: {
    parameters: {
      query?: never;
      header?: {
        /**
         * @description Identificador de correlación; se propaga a logs, trazas y proveedores externos.
         * @example 8d0c2f0e-5b1a-4f7e-9a51-2c1f0f6a9b11
         */
        'X-Correlation-ID'?: components['parameters']['CorrelationId'];
        /** @description Código IATA de la aerolínea white-label que usa el cliente. */
        'X-Tenant'?: components['parameters']['Tenant'];
      };
      path: {
        /** @description Localizador de la reserva (PNR). */
        locator: components['parameters']['Locator'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Reserva emitida. */
      200: {
        headers: {
          'X-Correlation-ID': components['headers']['CorrelationId'];
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Booking'];
        };
      };
      400: components['responses']['BadRequest'];
      404: components['responses']['NotFound'];
      409: components['responses']['Conflict'];
      /**
       * @description No se pudo emitir por una regla de negocio. Si la saga compensó,
       *     `bookingStatus` es `FAILED`.
       */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
    };
  };
  cancelBooking: {
    parameters: {
      query?: never;
      header?: {
        /**
         * @description Identificador de correlación; se propaga a logs, trazas y proveedores externos.
         * @example 8d0c2f0e-5b1a-4f7e-9a51-2c1f0f6a9b11
         */
        'X-Correlation-ID'?: components['parameters']['CorrelationId'];
        /** @description Código IATA de la aerolínea white-label que usa el cliente. */
        'X-Tenant'?: components['parameters']['Tenant'];
      };
      path: {
        /** @description Localizador de la reserva (PNR). */
        locator: components['parameters']['Locator'];
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        /**
         * @example {
         *       "reason": "El cliente cambió sus planes"
         *     }
         */
        'application/json': components['schemas']['CancelBookingRequest'];
      };
    };
    responses: {
      /** @description Reserva cancelada. */
      200: {
        headers: {
          'X-Correlation-ID': components['headers']['CorrelationId'];
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Booking'];
        };
      };
      400: components['responses']['BadRequest'];
      404: components['responses']['NotFound'];
      409: components['responses']['Conflict'];
    };
  };
}
